### ISSUE TITLE
PEP-8 refactor

### ISSUE THREAD

**Issue by stefsy** [SiliconValleyInsight/svi-training-a#1]
Read [PEP-8](https://www.python.org/dev/peps/pep-0008/) and refactor oglafparser_carlos.py

**Comment by marksteve** [comment]
It's not hard to memorize PEP-8. But while learning the convention, you can use this https://github.com/jcrocholl/pep8

**Comment by antoniocarlosortiz** [comment]
I use tox for checking pep8 compliance. Thanks!
