### ISSUE TITLE
Week 2 Code Review

### ISSUE THREAD

**Issue by marksteve** [SiliconValleyInsight/svi-training-a#2]
https://github.com/SiliconValleyInsight/svi-training-a/blob/master/code-samples/week2/Norvig/CS124-Week2-Reading-How%20to%20Write%20a%20Spelling%20Corrector.py#L22-L34

You got the idea but let me clarify things:
`train()` returns a `defaultdict`, not a tuple. the `.items()` method of a dict gives you a list of tuples `(key, value)`. You probably got what `defaultdict` was doing but just to explain further. `defaultdict` is a normal dict that allows you to pass in a constructor w/c gets called every time you try to access an undefined key from the dict. The return value of the constructor gets used as the default value for the undefined key. In this case, `lambda: 1` was our constructor.

**Comment by antoniocarlosortiz** [comment]
okay thanks!
